### PR TITLE
Update  Image Path  Meshery

### PR DESCRIPTION
**Pull request by Vi1234sh12**
Signed-off-by: Vi1234sh12 vishald41234@gmail.com

**Description**
Update Image Path 
This PR fixes #
https://github.com/layer5io/layer5/blob/master/.github/assets/images/meshery/meshery-logo-tag-light-text-side.png
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Vi1234sh12** [comment]
Hey @leecalcote, 

I'm Update Image Path just Look at This

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you, @Vi1234sh12. 👍 

Here is the URL that we'll need to use - https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/meshery/meshery-logo-tag-light-text-side.png. 

The github.com reference will return an html page, not an image, which is why we'll need to use raw.githubusercontent.com

**Comment by Vi1234sh12** [comment]
Signed-off-by: Vishal Dhanure <vishald41234@gmail.com>

**Comment by Vi1234sh12** [comment]
@leecalcote, as you say I'm again updating the path just look at this path correctly or not

**Review by leecalcote — APPROVED** [review]
Thank you, @Vi1234sh12

**Pull request merged**
